---
- name: DNS
  hosts: dns
  become: true
  roles:
    - role: rhel_dvd
      when: rhel_dvd_repo_enable | default(true) | bool
    - role: common
    - role: dns

- name: Registry
  hosts: registry
  become: true
  roles:
    - role: rhel_dvd
      when: rhel_dvd_repo_enable | default(true) | bool
    - role: common
    - role: registry

- name: Bastion
  hosts: bastion
  become: true
  roles:
    - role: common
    - role: bastion
